AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - Put BlogPost - Lambda Function
Parameters:
  Environment:
    Description: Environment
    Type: String
  S3BucketName:
    Description: S3 Bucket Name
    Type: String
  BlogPostTablePutItemPolicy:
    Description: BlogPost Table Policy
    Type: String
  RestApiIdParam:
    Description: REST API id
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/BlogPost/APIGateway/Id

Resources:
  BlogPostBucketPutObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for PutObject on S3 Bucket
      ManagedPolicyName:
        !Join [
          "_",
          [!Ref Environment, "BlogPostBucketPutObjectPolicy", "Policy"],
        ]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:PutObject"
            Resource:
              !Join [
                "",
                [
                  "arn:aws:s3:::",
                  !Ref Environment,
                  "-",
                  !Ref S3BucketName,
                  "/*",
                ],
              ]

  PutBlogPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["_", [!Ref Environment, PutBlogPostFn]]
      Description: Put Blogpost function
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 1
      Policies:
        - !Ref BlogPostBucketPutObjectPolicy
        - Fn::Join:
            [
              "",
              [
                "arn:aws:iam::",
                !Sub "${AWS::AccountId}",
                ":policy/",
                !Ref BlogPostTablePutItemPolicy,
              ],
            ]
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /blogpost
            Method: POST
            RestApiId: !Ref RestApiIdParam
      Environment:
        Variables:
          BlogPostContentBucketName:
            !Join ["-", [!Ref Environment, !Ref S3BucketName]]
          BlogPostTableName:
            Fn::Join: ["_", [!Ref Environment, escoladesoftware_blog_blogpost]]
          Region: us-east-1
